[package]
name = "rustwget"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "2.33"
reqwest = { version = "0.11", features = ["blocking"] }
url = "2.2"

[dev-dependencies]
mockito = "0.31"
tempfile = "3.2"